version: '3.1'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=homestead
          - POSTGRES_PASSWORD=secret
        ports:
          - '5432:5432'
        