import Head from 'next/head'
import Link from "next/link"
import { appAxios } from '../utils/appAxios'
import {useRouter} from "next/router"

export default function Home({data}) {
    console.log(data);

  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { data.map((mydata) => (
           <div key={mydata} aria-label="group of cards" tabIndex="0" className="focus:outline-none py-8 w-full">
           <div className="lg:flex items-center justify-center w-full">
               <div tabIndex="0" aria-label="card 1" className="focus:outline-none lg:w-4/12 lg:mr-7 lg:mb-0 mb-7 bg-white p-6 shadow rounded">
                   <div className="flex items-center border-b border-gray-200 pb-6">
                       <img src="https://cdn.tuk.dev/assets/components/misc/doge-coin.png" alt="coin avatar" className="w-12 h-12 rounded-full" />
                       <div className="flex items-start justify-between w-full">
                           <div className="pl-3 w-full">
                               <p tabIndex="0" className="focus:outline-none text-xl font-medium leading-5 text-gray-800">{mydata.newstitle}</p>
                               <p tabIndex="0" className="focus:outline-none text-sm leading-normal pt-2 text-gray-500">Trends : {mydata.newsrate}</p>
                           </div>
                           <div role="img" aria-label="bookmark">
                               
                           </div>
                       </div>
                   </div>
                   <div className="px-2">
                       <p tabIndex="0" className="focus:outline-none text-sm leading-5 py-4 text-gray-600">{mydata.newsdesc}</p>
                       <div tabIndex="0" className="focus:outline-none flex">
                           <div className="py-2 px-4 text-xs leading-3 text-indigo-700 rounded-full bg-indigo-100">#{mydata.newscategory}</div>
                           <a className='ml-5 bg-red-400 text-white p-1 rounded-2xl'><Link href={`/news/${mydata.id}`}>Read </Link></a>

                       </div>
                   </div>
               </div>
           </div>
       </div>
 
       
      ))}
     
    </>
    
  )
}

export async function getStaticProps(){

    const {data} = await appAxios.get("api/news")
   
    return {
        props: {
            data
        }
    }
}

